### ISSUE TITLE
/questionsで質問の投票数をもらっていない

### ISSUE THREAD

**Issue by bbbbbbbbbbbbb1** [RochUP/frontend#78]
/questionsで質問の投票数をサーバから送っていなかったので，voteNumを返り値に含めることにしました．
stoplight: https://rochup.stoplight.io/studio/rochup?source=_yrHVsNNNcIQk2dw57wOz&symbol=%252Fp%252FRochUP.yaml%252Fpaths%252F%7E1questions%252Fpost

**Comment by KOKI9861** [comment]
対応しました．
